In [1]:
import numpy as np

In [2]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])

In [3]:
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [4]:
type(a)

numpy.ndarray

In [5]:
a*5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
a[5:]

array([], dtype=float64)

In [9]:
a = np.array(['a','b','c'])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.dtype

dtype('<U1')

In [12]:
a = np.arange(8, dtype=np.float)

In [13]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [17]:
#c = np.arange((1,2))

In [15]:
c

array([0, 1])